name: "Acceptance Test Action"
description: "Cache artifacts like dependencies and build outputs to improve workflow execution time"
author: "GitHub"
inputs:
  forceTestAcc:
    description: "if unconditionally trigger tests"
    required: true
  filters:
    description: "files to detect if tests should be run"
    required: true
  testRegex:
    description: "regular expression for test methods"
    required: true
runs:
  using: "composite"
  steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: ${{ inputs.filters }}
    - name: Set up Go
      if: ${{ inputs.forceTestAcc || steps.filter.outputs.src == 'true'}}
      uses: actions/setup-go@v4
      with:
        go-version-file: "go.mod"
    - name: Acceptance Tests
      if: ${{ inputs.forceTestAcc || steps.filter.outputs.src == 'true'}}
      env:
        TEST_REGEX: ${{ inputs.testRegex }}
      shell: bash
      run: make testacc
