name: "Acceptance Test Action"
description: "Cache artifacts like dependencies and build outputs to improve workflow execution time"
author: "GitHub"
inputs:
  forceTestAcc:
    description: "if unconditionally trigger tests"
    required: true
  filters:
    description: "files to detect if tests should be run"
    required: true
runs:
  using: "composite"
  steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          src: ${{ inputs.filters }}
    - name: Print hello
      shell: bash
      run: |
        echo HELLO HELLO 
        echo boolean: ${{ inputs.forceTestAcc }} : ok
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: "go.mod"
    - name: Acceptance Tests
      if: ${{ steps.filter.outputs.src == 'true'}}
      shell: bash
      run: make testacc
    - name: Print bye
      shell: bash
      run: echo BYE BYE
