name: Update Atlas Go SDK

# Checks if a new Atlas Go SDK version is available and creates a pull request adjusting version in codebase. Runs once per week and can be triggered manually.
on:
 schedule:
   - cron: "30 8 * * TUE" # Every Tuesday at 8:30 AM 
 workflow_dispatch:
  
jobs:
  update-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
        with:
          go-version-file: 'go.mod'
      - name: Trigger Go proxy cache refresh
        run: |
          LATEST_SDK_TAG=$(curl -sSfL https://api.github.com/repos/mongodb/atlas-sdk-go/releases/latest | jq -r '.tag_name')
          LATEST_SDK_RELEASE=$(echo "${LATEST_SDK_TAG}" | cut -d '.' -f 1)
          echo "tag: ${LATEST_SDK_TAG}, release: ${LATEST_SDK_RELEASE}"
          curl -sSfL "https://proxy.golang.org/go.mongodb.org/atlas-sdk/${LATEST_SDK_RELEASE}/@v/${LATEST_SDK_TAG}.info"
      - name: Update files
        run:  make tools update-atlas-sdk
      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@8b28bea118e7723e4672bc7ac323bcd26f271ec4
        id: verify-changed-files
      - name: Create PR
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        with:
          title: "chore: Updates Atlas Go SDK"
          commit-message: "build(deps): bump go.mongodb.org/atlas-sdk"
          delete-branch: true
          branch: atlas-sdk-update
          body: Automatic update for MongoDB Atlas Go Client SDK
  